# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestfindname():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testfindname(self):
    self.driver.get("https://www.lazada.vn/#?")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.ID, "q").click()
    self.driver.find_element(By.ID, "q").send_keys("ihpone 15 pro")
    self.driver.find_element(By.ID, "q").send_keys(Keys.DOWN)
    self.driver.find_element(By.ID, "q").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".Bm3ON:nth-child(1) .buTCk").click()
    assert self.driver.find_element(By.LINK_TEXT, "Apple iPhone 15 Pro Max 256GB Chính hãng (VN/A)").text == "Apple iPhone 15 Pro Max 256GB Chính hãng (VN/A)"
  
