# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    # Test name: search
    # Step # | name | target | value
    # 1 | open | https://cellphones.com.vn/ | 
    self.driver.get("https://cellphones.com.vn/")
    # 2 | setWindowSize | 1050x840 | 
    self.driver.set_window_size(1050, 840)
    # 3 | click | id=inp$earch | 
    self.driver.find_element(By.ID, "inp$earch").click()
    # 4 | type | id=inp$earch | iphone 1
    self.driver.find_element(By.ID, "inp$earch").send_keys("iphone 1")
    # 5 | type | id=inp$earch | iphone 16
    self.driver.find_element(By.ID, "inp$earch").send_keys("iphone 16")
    # 6 | click | css=.svg-inline--fa | ${KEY_ENTER}
    self.driver.find_element(By.CSS_SELECTOR, ".svg-inline--fa").click()
    # 7 | click | css=.search-sort-item:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".search-sort-item:nth-child(2)").click()
    # 8 | click | css=.product-info-container:nth-child(1) .product__img | 
    self.driver.find_element(By.CSS_SELECTOR, ".product-info-container:nth-child(1) .product__img").click()
  
