# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    self.driver.get("https://www.lazada.vn/#?")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.ID, "q").click()
    self.driver.find_element(By.ID, "q").send_keys("iphone 15 pro max")
    self.driver.find_element(By.LINK_TEXT, "SEARCH").click()
    self.driver.find_element(By.LINK_TEXT, "(Siêu Tiệc Giáng Sinh 06-08.12) iPhone 15 Pro Max - Hàng Chính Hãng VN/A").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pdp-mod-product-badge-title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pdp-mod-product-badge-title").click()
    self.driver.find_element(By.ID, "block-BDipfo2QZad").click()
    element = self.driver.find_element(By.ID, "block-BDipfo2QZad")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    assert self.driver.find_element(By.CSS_SELECTOR, ".pdp-mod-product-badge-title").text == "(Siêu Tiệc Giáng Sinh 06-08.12) iPhone 15 Pro Max - Hàng Chính Hãng VN/A"
    self.driver.close()
  
