# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.keys import Keys

class TestSearchlazada:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
  
    def teardown_method(self, method):
        self.driver.quit()
  
    def test_searchlazada(self):
        # Mở trang Lazada
        self.driver.get("https://www.lazada.vn/")
        self.driver.set_window_size(1050, 840)
        
        # Chờ hộp tìm kiếm xuất hiện
        wait = WebDriverWait(self.driver, 20)
        search_box = wait.until(EC.presence_of_element_located((By.ID, "q")))
        
        # Nhập từ khóa và tìm kiếm
        search_box.click()
        search_box.send_keys("áo hoodie")
        search_box.send_keys(Keys.RETURN)  # Nhấn Enter để tìm kiếm
        
        # Chờ danh sách sản phẩm xuất hiện
        first_product = wait.until(
            EC.presence_of_element_located(
                (By.CSS_SELECTOR, ".Bm3ON:nth-child(1) ._95X4G img")
            )
        )
        
        # Di chuột qua và nhấn vào sản phẩm đầu tiên
        actions = ActionChains(self.driver)
        actions.move_to_element(first_product).perform()
        first_product.click()
